package com.zubairmuwwakil.marketdata.demo;

import com.zubairmuwwakil.marketdata.model.entity.ApiQuotaUsage;
import com.zubairmuwwakil.marketdata.model.entity.CorporateAction;
import com.zubairmuwwakil.marketdata.model.entity.PipelineRun;
import com.zubairmuwwakil.marketdata.model.entity.PipelineRunType;
import com.zubairmuwwakil.marketdata.model.entity.PipelineStatus;
import com.zubairmuwwakil.marketdata.model.entity.PriceCandle;
import com.zubairmuwwakil.marketdata.model.entity.WatchlistSymbol;
import com.zubairmuwwakil.marketdata.repository.ApiQuotaUsageRepository;
import com.zubairmuwwakil.marketdata.repository.CorporateActionRepository;
import com.zubairmuwwakil.marketdata.repository.IngestionQuarantineRepository;
import com.zubairmuwwakil.marketdata.repository.PipelineRunRepository;
import com.zubairmuwwakil.marketdata.repository.PriceCandleRepository;
import com.zubairmuwwakil.marketdata.repository.WatchlistSymbolRepository;
import com.zubairmuwwakil.marketdata.service.indicator.IndicatorCalculationService;
import com.zubairmuwwakil.marketdata.service.ingestion.QuotaService;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;

@Configuration
@Profile("demo")
public class DemoDataSeeder {

    private static final ZoneId NEW_YORK = ZoneId.of("America/New_York");

    @Bean
    ApplicationRunner seedDemoData(DemoDatasetFactory datasetFactory,
                                   JdbcTemplate jdbcTemplate,
                                   WatchlistSymbolRepository watchlistRepository,
                                   PriceCandleRepository priceCandleRepository,
                                   CorporateActionRepository corporateActionRepository,
                                   PipelineRunRepository pipelineRunRepository,
                                   ApiQuotaUsageRepository quotaUsageRepository,
                                   IndicatorCalculationService indicatorCalculationService,
                                   IngestionQuarantineRepository quarantineRepository) {
        return args -> {
            createQuarantineTable(jdbcTemplate);
            if (priceCandleRepository.count() > 0) {
                return;
            }

            DemoDatasetFactory.DemoDataset dataset = datasetFactory.dataset();
            seedWatchlist(dataset, watchlistRepository);
            seedCandles(dataset, priceCandleRepository);
            seedCorporateActions(dataset, corporateActionRepository);
            seedIndicators(dataset, indicatorCalculationService);
            seedRunsAndQuarantine(dataset, pipelineRunRepository, quarantineRepository);
            seedQuota(quotaUsageRepository);
        };
    }

    private void createQuarantineTable(JdbcTemplate jdbcTemplate) {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS ingestion_quarantine (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    symbol VARCHAR(10),
                    trade_date DATE,
                    reason VARCHAR(64) NOT NULL,
                    payload CLOB NOT NULL,
                    source VARCHAR(32),
                    run_id BIGINT,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
                )
                """);
    }

    private void seedWatchlist(DemoDatasetFactory.DemoDataset dataset,
                               WatchlistSymbolRepository watchlistRepository) {
        List<WatchlistSymbol> watchlist = new ArrayList<>();
        for (String symbol : dataset.activeSymbols()) {
            watchlist.add(WatchlistSymbol.builder().symbol(symbol).active(true).build());
        }
        for (String symbol : dataset.inactiveSymbols()) {
            watchlist.add(WatchlistSymbol.builder().symbol(symbol).active(false).build());
        }
        watchlistRepository.saveAll(watchlist);
    }

    private void seedCandles(DemoDatasetFactory.DemoDataset dataset,
                             PriceCandleRepository priceCandleRepository) {
        List<PriceCandle> candles = new ArrayList<>();
        dataset.candlesBySymbol().forEach((symbol, rows) -> rows.forEach(candle -> candles.add(
                PriceCandle.builder()
                        .symbol(symbol)
                        .tradeDate(candle.tradeDate())
                        .open(candle.open())
                        .high(candle.high())
                        .low(candle.low())
                        .close(candle.close())
                        .volume(candle.volume())
                        .adjusted(false)
                        .source("DEMO")
                        .build()
        )));
        priceCandleRepository.saveAll(candles);
    }

    private void seedCorporateActions(DemoDatasetFactory.DemoDataset dataset,
                                      CorporateActionRepository corporateActionRepository) {
        List<CorporateAction> actions = dataset.corporateActions().stream()
                .map(seed -> CorporateAction.builder()
                        .symbol(seed.symbol())
                        .actionDate(seed.actionDate())
                        .actionType(seed.actionType())
                        .splitFactor(seed.splitFactor())
                        .dividend(seed.dividend())
                        .build())
                .toList();
        corporateActionRepository.saveAll(actions);
    }

    private void seedIndicators(DemoDatasetFactory.DemoDataset dataset,
                                IndicatorCalculationService indicatorCalculationService) {
        for (String symbol : dataset.candlesBySymbol().keySet()) {
            indicatorCalculationService.calculateForSymbol(symbol);
        }
    }

    private void seedRunsAndQuarantine(DemoDatasetFactory.DemoDataset dataset,
                                       PipelineRunRepository pipelineRunRepository,
                                       IngestionQuarantineRepository quarantineRepository) {
        Instant now = Instant.now();
        PipelineRun backfill = pipelineRunRepository.save(PipelineRun.builder()
                .runDate(dataset.from())
                .status(PipelineStatus.SUCCESS)
                .runType(PipelineRunType.BACKFILL)
                .symbolsExpected(dataset.candlesBySymbol().size())
                .symbolsProcessed(dataset.candlesBySymbol().size())
                .symbolsFailed(0)
                .retryCount(0)
                .startedBy("demo-seed")
                .requestedFrom(dataset.from())
                .requestedTo(dataset.to())
                .startedAt(now.minusSeconds(7 * 24 * 3600))
                .finishedAt(now.minusSeconds(7 * 24 * 3600 - 120))
                .build());

        PipelineRun partial = pipelineRunRepository.save(PipelineRun.builder()
                .runDate(dataset.qualityGapDate())
                .status(PipelineStatus.PARTIAL)
                .runType(PipelineRunType.DAILY)
                .symbolsExpected(dataset.activeSymbols().size() + dataset.inactiveSymbols().size())
                .symbolsProcessed(dataset.activeSymbols().size())
                .symbolsFailed(1)
                .retryCount(1)
                .startedBy("demo-seed")
                .errorMessage(dataset.qualitySymbol() + ": one malformed row diverted to quarantine.")
                .startedAt(now.minusSeconds(2 * 24 * 3600))
                .finishedAt(now.minusSeconds(2 * 24 * 3600 - 90))
                .build());

        pipelineRunRepository.save(PipelineRun.builder()
                .runDate(dataset.to())
                .status(PipelineStatus.SUCCESS)
                .runType(PipelineRunType.DAILY)
                .symbolsExpected(dataset.activeSymbols().size())
                .symbolsProcessed(dataset.activeSymbols().size())
                .symbolsFailed(0)
                .retryCount(0)
                .startedBy("demo-seed")
                .startedAt(now.minusSeconds(24 * 3600))
                .finishedAt(now.minusSeconds(24 * 3600 - 75))
                .build());

        quarantineRepository.save(
                dataset.qualitySymbol(),
                dataset.qualityGapDate(),
                "missing_price",
                "{\"symbol\":\"%s\",\"tradeDate\":\"%s\",\"close\":null}".formatted(dataset.qualitySymbol(), dataset.qualityGapDate()),
                "DEMO",
                partial.getId()
        );
    }

    private void seedQuota(ApiQuotaUsageRepository quotaUsageRepository) {
        LocalDate today = LocalDate.now(NEW_YORK);
        quotaUsageRepository.findByProviderAndUsageDate(QuotaService.PROVIDER, today)
                .orElseGet(() -> quotaUsageRepository.save(ApiQuotaUsage.builder()
                        .provider(QuotaService.PROVIDER)
                        .usageDate(today)
                        .callsUsed(4)
                        .callsLimit(QuotaService.DAILY_LIMIT)
                        .build()));
    }
}
